language: php
php:
  - 7.4

before_script:
  - composer install --dev --no-interaction

script:
  - php vendor/bin/phpunit -c phpunit.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls -v