version: '3.7'
services:
  php:
    build: ./.docker/php
    restart: unless-stopped
    volumes:
      - ./:/whatsapp
      - ~/.composer:/root/.composer
    links:
      - selenium-hub
    environment:
      - XDEBUG_CONFIG
      - TZ
      - TELEGRAM_BOT_TOKEN
      - TELEGRAM_CHAT_ID
      - LOG_DIR

  chrome:
    image: selenium/node-chrome:4.1.1-20211217
    shm_size: 2gb
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    ports:
      - "5900:5900"
    environment:
      - SE_EVENT_BUS_HOST
      - SE_EVENT_BUS_PUBLISH_PORT
      - SE_EVENT_BUS_SUBSCRIBE_PORT

  firefox:
    image: selenium/node-firefox:4.1.1-20211217
    shm_size: 2gb
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    ports:
      - "5901:5900"
    environment:
      - SE_EVENT_BUS_HOST
      - SE_EVENT_BUS_PUBLISH_PORT
      - SE_EVENT_BUS_SUBSCRIBE_PORT

  selenium-hub:
    image: selenium/hub:4.1.1-20211217
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
