version: '3.7'
services:
  php7:
    build: ./.docker/php7
    restart: unless-stopped
    volumes:
      - ./:/whatsapp
      - ~/.composer:/root/.composer
    links:
      - selenium-hub
    environment:
      XDEBUG_CONFIG: "remote_host=172.17.0.1 remote_enable=1"
    command: composer install

  chrome:
    image: selenium/node-chrome-debug:3.141.59-20200525
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    ports:
      - "5900:5900"
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444

  firefox:
    image: selenium/node-firefox-debug:3.141.59-20200525
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    ports:
      - "5901:5900"
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444

  selenium-hub:
    image: selenium/hub:3.141.59-20200525
    ports:
      - "4443:4444"
